<?php

/**
 * @file
 * Allows the creation of custom blocks through the user interface.
 */
function qldc_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'node_congdan_form') {
    $form['#theme'] = 'dongcuong_node_congdan_form';
    $form['#cache'] = ['max-age' => 0];
  }

  if ($form_id == 'node_xac_nhan_dan_su_form') {
    //dsm($form['title']['widget'][0]['value']);
    $form['#theme'] = 'dongcuong_node_xac_nhan_dan_su_form';
    $form['#cache'] = ['max-age' => 0];
    $form['title']['widget'][0]['value']['#autocomplete_route_name'] = 'qldc.xnds_autocomplete.hovaten';
  }  
}

function qldc_options_list_alter(array &$options, array $context) {
  unset($options['_none']);
}
